# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2
# Personal info
name: WAN, Ching Pui
title: Student researcher, Software engineer
email: cpwan@ust.hk
website: cpwan.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  cpwan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: cpwan
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Resume in pdf
  icon: fas fa-file-pdf
  url: https://cpwan.github.io/downloads/WAN.pdf

# - title: Email link
#   icon: fas fa-envelope-square
#   url: "mailto:cpwan@ust"

# - title: Skype
#   icon: fab fa-skype
#   url: "skype:live:cpwan_9?chat"

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-MG7GSB5"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ching Pui. You can also call me Patrick. I'm from Hong Kong. I'm doing a master in Computer Science. I am interested in topics in privacy-preserving AI and computer vision.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Robust Federated Learning with Attack-Adaptive Aggregation
        link: https://github.com/cpwan/Attack-Adaptive-Aggregation
        # link_text: Project Website
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/cpwan/Attack-Adaptive-Aggregation
          - title: Paper
            icon: fas fa-book
            url: https://arxiv.org/abs/2102.05257
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title:  Master thesis
        description: | # this will include new lines to allow paragraphs
            Federated learning is vulnerable to various attacks, such as model poisoning and backdoor attacks, even if some existing defense strategies are used. 
            To address this challenge, we propose an attack-adaptive aggregation strategy to defend against various attacks for robust federated learning. 
            The proposed approach is based on training a neural network with an attention mechanism that learns the vulnerability of federated learning models from a set of plausible attacks. 
            To the best of our knowledge, our aggregation strategy is the first one that can be adapted to defend against various attacks in a data-driven fashion. 
            Our approach has achieved competitive performance in defending model poisoning and backdoor attacks in federated learning tasks on image and text datasets.
        
      - layout: top-middle
        title: SHAP for Visual Explanations of Time Series Models
        sub_title:  Course project
        caption: Sep. 2020 - Dec. 2020
        link: https://github.com/comp5331-Xtimeseries/Xtimeseries
        # link_text: Project Website
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/comp5331-Xtimeseries/Xtimeseries
          - title: Paper
            icon: fas fa-book
            url: https://github.com/comp5331-Xtimeseries/Xtimeseries/blob/main/COMP_5331_Final_Report.pdf
          - title: Slides
            icon: fas fa-file-powerpoint
            url: https://github.com/comp5331-Xtimeseries/Xtimeseries/blob/main/slides.pdf
        description: | # this will include new lines to allow paragraphs
            - Implemented LST-Net, TPA-LSTM, mWDN for time sereis prediction with `PyTorch` and `Tensorflow`
            - Performed experiments on multivatiate time sereis datasets
            - Analyzed the effecitveness of SHAP for visual explanations of the time series models


      - layout: top-middle
        title: Steel Defect Detection with Deep Semantic Segmentation
        sub_title:  Course project
        caption: Sep. 2019 - Dec. 2019
        link: https://github.com/cpwan/steel-defect-detection
        # link_text: Project Website
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/cpwan/steel-defect-detection
          - title: Paper
            icon: fas fa-book
            url: https://github.com/cpwan/steel-defect-detection/blob/drn/Steel%20defect%20detection%20with%20deep%20semantic%20segmentation.pdf

        description: | # this will include new lines to allow paragraphs
            - Implemented U-net and Context Aggregated Network for semantic segmentation with `PyTorch`
            - Performed experiments on binary cross entropy loss and dice loss
            - Explored the shortcuts issues with dice loss

      - layout: top-middle
        title: Colorization with Generative Adversarial Network
        sub_title:  Independent study
        caption: Feb. 2019 - Jun. 2019
        link: https://github.com/cpwan/colorization-with-cGAN
        # link_text: Project Website
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/cpwan/colorization-with-cGAN
          - title: Paper
            icon: fas fa-book
            url: https://github.com/cpwan/colorization-with-cGAN/blob/master/report.pdf

        description: | # this will include new lines to allow paragraphs
            - Implemented U-net for image style transfer with `PyTorch`
            - Performed experiments on regularizations and conditional discriminator
            - Performed colorization on various sources of training data

      - layout: top-middle
        title: Voice Spoofing with Machine Learning
        sub_title:  Course project
        caption: Sep. 2018 - Dec. 2018

        description: | # this will include new lines to allow paragraphs
            - Implemented GAN for voice synthesis on celebrities with `PyTorch`
            - Built voice identification system against generated voice with Gaussian Mixture model

            
      - layout: top-middle
        title: Travel Agent Chatbot
        sub_title:  Course project
        caption: Sep. 2017 - Dec. 2017

        description: | # this will include new lines to allow paragraphs
            - Built a chatbot on LINE messenger using `Java Spring Boot`, `JDBC` and `DialogFlow`
            - Implemented a database management system with `Django`
            - Practiced agile with pair programming and weekly sprint planning with Trello

      - layout: top-middle
        title: Low-Rank and Sparsity Reconstruction in Data Science
        sub_title:  Undergraduate Research Opportunity Program
        caption: Sep. 2016 - Dec. 2016

        description: | # this will include new lines to allow paragraphs
            - Perform literature reviews on sparse coding and dictionary learning
            - Implemented text recognition with K-SVD on `MatLab`



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hong Kong University of Science & Technology
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Teaching assistant
        caption: Feb. 2020 - Dec. 2020

        description: | # this will include new lines to allow paragraphs
            - Responsible for two courses: a UG level OOP course, a PG level AI course 
            - Delivered a tutorial on `C++` STL, designed coding assignments on template, operator overloading, friends 
            - Designed written& coding assignments on perceptron/ search/ MDP/ knowledge representation/ game theory 
            - Held AI contests for students to compete in a navigation mission with the AI methods they learned

      - layout: left
        title: Google LA x Institute for Pure & Applied Mathematics
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Research Internship in Los Angeles
        caption: Jun. 2018 - Aug. 2018
        quote: >
          Why bother annotating every sample when most of them are negative anyway? Verify only the predicted positive samples and tune the classifiers, as well as their ensemble!
        description: | # this will include new lines to allow paragraphs
            - Project on “Extreme rare events classification with predicted positive data” 
            - Developed algorithms for effective classifiers ensemble on limited training samples 
            - Applied the software developed on advertising security 
            - Delivered weekly meetings, reports, oral presentations with industrial sponsor from Google LA

      - layout: left
        title: Microsoft Research Asia x HKUST
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Research Internship in Hong Kong
        caption: Jun. 2017 - Aug. 2017
        quote: >
          What is the best trade-off between convergence and communication overhead in distributed machine learning? How about convex vs non-convex case? Synchronous vs asynchronous SGD?

        description: | # this will include new lines to allow paragraphs
            - Project on “Efficient Communication in Distributed Machine Learning” 
            - Implemented distributive machine learning with Microsoft’s deep learning framework (`CNTK`) on `C++ `
            - Analyzed criteria for efficient distributed machine learning 
            - Performed experiments on image classification, recommendation system, and language translation tasks

  - title: Competition # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BigDatathon, HKUST x Radica
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: First runner-up, Best Enterpreneur Award
        caption: Dec. 2017
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Prototyped a ranking system for restaurants in Hong Kong based on sentiment analysis
            - Extracted comments on restaurants from Instagram with `Selenium`
            - Performed sentiment analysis on Instagram posts with Stanford CoreNLP
            Projects

      - layout: left
        title: CodeIT Suisse, Credit Suisse
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: The 5th team
        caption: Sep. 2019
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - A coding competition on algorithms and time-series analysis


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hong Kong University of Science & Technology
        caption: Sep. 2019 – Exp. Jul. 2021
        sub_title: MPhil in Computer Science and Engineering

        description: | # this will include new lines to allow paragraphs
          I did courses in Algorithms, Optimization in Machine Learning, Deep learning, Data mining, Software Engineering, Security, 
          
          I worked on the thesis *Robust Federated Learning with Attack-Adaptive Aggregation*. 
          The work explores the vulnerability of deep learning models trained in the federated learning setting. It learns to detect possible corrupted model updates in a self-supervised manner.

      - layout: left
        title: Hong Kong University of Science & Technology
        caption: Sep. 2015 - Aug. 2019
        sub_title: "B.Sc in Mathematics and Computer Science – GPA: 3.9/4.3, First Class Honors"
        description: | # this will include new lines to allow paragraphs
          Highlight coursework: Algorithm, Software Engineering, OOP, Probability, Statistical Inference, Analysis

      - layout: left
        title: ETH Zürich (Swiss Federal Institute of Technology in Zurich)
        caption: Sep. 2018 - Jan. 2019
        sub_title: "Exchange program – GPA: 5.3/6.0"

        description: | # this will include new lines to allow paragraphs
          Highlight coursework: Deep Learning, Advanced Machine Learning, Computer Vision

  - title: Hobbies and interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      Apart from machine learning and software engineering, I am also interested in:
      - Gaming 
      - Manga and Anime
      - Traveling
# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
